---
name: ðŸ“ Theme request
description: Request a new theme be added to the project
title: "[Theme request] "
labels: ["is:theme", "needs-triage"]
projects: ["doomemacs/2"]
body:
- type: markdown
  attributes:
    value: |
      > [!IMPORTANT]
      > It takes us a *long* time to get around to theme requests. Consider submitting a pull request instead.
- type: textarea
  attributes:
    label: What theme(s) are you requesting?
    description: |
      Include links to any upstream resources for this theme, like where the original project lives, screenshots, color palettes, etc.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Disclosures
    description:
      Check off any that apply to help us assess your issue(s) more accurately.
    options:
      - label: I'm the author/maintainer of the theme(s) I'm requesting.
      - label: I'm willing to maintain the theme(s) if added.
      - label: This issue was written with/by AI.
